version: '3.8'

services:
  test-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=assessment_test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - ./src/migrations:/docker-entrypoint-initdb.d